using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Threading;
using Newtonsoft.Json.Linq;
using WebSocketSharp;
using ZurvanBot.Discord;
using ZurvanBot.Discord.Gateway;
using ZurvanBot.Discord.Resources.Objects;
using ZurvanBot.Discord.Resources.Params;
using ZurvanBot.Util;
using ZurvanBot.Util.HTTP;

namespace ZurvanBot
{
    internal class Program
    {
        public static void Main(string[] args)
        {   
            // Console.WriteLine(DateTime.Now.ToString("dd.MM.yyyy-HH:mm:ss"));

            if (!File.Exists("bot_token.txt"))
                return;
            var token = File.ReadAllText("bot_token.txt").Trim();
            if (token.Equals(""))
                return;
            
            var sentences = new string[]
            {
                "The voice arbitrates the poised hope.",
                "The reason terminates the design.",
                "The sea spearheads the attempt.",
                "The love tracks the soup.",
                "The bite revises the incredible look.",
                "The taste allocates the smell.",
                "The stretch mentors the witty part.",
                "The destruction mediates the damage.",
                "The time gathers the discovery.",
                "The leather simplifys the didactic rub.",
                "The ablaze steel values the room.",
                "The answer boosts the smash.",
                "The unadvised idea minimizes the pain.",
                "The eight noise packages the rain.",
                "The limit assumes the shake.",
                "The start reasons the elegant sleep.",
                "The profit spearheads the apparatus.",
                "The list forwards the voice.",
                "The judicious shade discharges the crush.",
                "The amused effect helps the bite.",
                "The nutty company recalls the heat.",
                "The education gathers the country.",
                "The copy accelerates the grouchy fire.",
                "The abundant wash exchanges the protest.",
                "The reaction contributes the sex.",
                "The judge unifys the miscreant look.",
                "The direction shows the gigantic science.",
                "The easy building details the tin.",
                "The insect generates the prickly experience.",
                "The view markets the payment.",
                "The record debugs the nutritious range.",
                "The way installs the noiseless wave.",
                "The swim solicits the fragile connection.",
                "The unit hires the plant.",
                "The uptight division distributes the manager.",
                "The stop establishs the gusty competition.",
                "The payment employs the fold.",
                "The decision stages the dusty swim.",
                "The copper integrates the flower.",
                "The purpose identifys the cold motion.",
                "The harmonious canvas builds the noise.",
                "The porter boughts the exultant limit.",
                "The machine inventorys the year.",
                "The gigantic pull prepares the ice.",
                "The knowledge generates the brainy comparison.",
                "The unadvised connection straightens the fact.",
                "The sand negotiates the mindless rest.",
                "The sedate wood reviews the owner.",
                "The helpless reward rehabilitates the love.",
                "The tin plans the robust money.",
                "The earth reports the massive paint.",
                "The ragged loss standardizes the quality.",
                "The stone encourages the merciful flame.",
                "The fold chairs the disease.",
                "The family appoints the complex stone.",
                "The glib act administers the minute.",
                "The rest eliminates the nondescript driving.",
                "The stone eliminates the aware example.",
                "The linen stages the print.",
                "The road pilots the wide-eyed guide.",
                "The page specializes the annoying level.",
                "The guide learns the ruddy look.",
                "The division corresponds the unused manager.",
                "The cause connects the opposite discussion.",
                "The dispensable wound depreciateds the sound.",
                "The year forecasts the whispering reward.",
                "The coal consolidates the judge.",
                "The religion aides the son.",
                "The reason diversifys the towering powder.",
                "The wood facilitates the absorbed smell.",
                "The bumpy top programs the turn.",
                "The makeshift motion lectures the sound.",
                "The hospitable blood devises the addition.",
                "The look enumerates the functional trick.",
                "The goofy look diagrams the base.",
                "The force segments the sort.",
                "The measure acts the internal wash.",
                "The snobbish plant records the competition.",
                "The hope broadens the wanting stitch.",
                "The plant integrates the silk.",
                "The lowly bite publishs the industry.",
                "The tendency zero ins the waste.",
                "The danger trades the reward.",
                "The natural verse refines the request.",
                "The selection acts the noxious slip.",
                "The science identifys the list.",
                "The overjoyed behavior diagrams the shade.",
                "The economic peace automates the news.",
                "The unnatural limit collects the opinion.",
                "The care judges the agreeable mist.",
                "The wind upgrades the four question.",
                "The voice utilizes the food.",
                "The teaching licenses the lush rain.",
                "The bit directs the homeless sense.",
                "The discussion relateds the righteous silk.",
                "The scattered servant appoints the burn.",
                "The teaching fabricates the division.",
                "The sand authorizes the silk.",
                "The silk manufactures the past quality.",
                "The burn participates the detailed silk.",
                "The comfort interfaces the sort.",
                "The time regulates the fold.",
                "The omniscient reading reconciles the food.",
                "The advertisement completes the self.",
                "The number rehabilitates the strange steam.",
                "The cough publicizes the reward.",
                "The paint solves the zany oil.",
                "The fight completes the driving.",
                "The gusty digestion discloses the position.",
                "The competition earns the acoustic pain.",
                "The turn settles the deeply effect.",
                "The plant converts the wakeful meal.",
                "The tiny design anticipates the sand.",
                "The shock interfaces the lift.",
                "The dazzling woman heads the list.",
                "The chivalrous wound uphelds the shock.",
                "The upbeat act enlarges the order.",
                "The juvenile year zoom ins the rice.",
                "The punishment starts the envious trade.",
                "The third machine reduces the weather.",
                "The swim boughts the machine.",
                "The jazzy move reviews the representative.",
                "The test simplifys the damage.",
                "The existence negotiates the moaning run.",
                "The room motivates the business.",
                "The detailed lift retains the effect.",
                "The careful fear appoints the top.",
                "The taste refers the meat.",
                "The coal preserves the scandalous comfort.",
                "The war modifys the rest.",
                "The idea assembles the well-groomed food.",
                "The smile quantifys the river.",
                "The fight founds the digestion.",
                "The fold orientates the instrument.",
                "The organisation transforms the value.",
                "The direction depreciateds the noiseless music.",
                "The connection accommodates the top.",
                "The near sign reviews the disease.",
                "The body collects the day.",
                "The religion licenses the man.",
                "The friend revitalizes the smell.",
                "The hungry night calculates the value.",
                "The measure upgrades the noisy song.",
                "The selection centralizes the unwritten front.",
                "The dreary religion collects the desire.",
                "The wood officiates the yielding government.",
                "The learning familiarizes the ablaze peace.",
                "The crack narrates the hurt weight.",
                "The sense spearheads the awake value.",
                "The ice canvasss the manager.",
                "The sneeze streamlines the discreet meat.",
                "The recondite edge shows the size.",
                "The daughter influences the nasty meal.",
                "The argument defends the way.",
                "The start upgrades the gleaming wine.",
                "The wary existence inventorys the amusement.",
                "The development accommodates the swim.",
                "The butter projects the space.",
                "The madly distribution reduces the effect.",
                "The story evaluates the clean writing.",
                "The history employs the shivering earth.",
                "The paper moderates the industry.",
                "The learning researchs the huge cotton.",
                "The stretch formulates the glass.",
                "The good color transmits the reaction.",
                "The balance fine-tunes the well-to-do stop.",
                "The nosy crush maps the wind.",
                "The touch times the tenuous detail.",
                "The point presides the bouncy help.",
                "The sharp music strengthens the question.",
                "The blow delegates the jobless wash.",
                "The cold surprise justifys the mountain.",
                "The sea spearheads the clean attempt.",
                "The twist distinguishs the mist.",
                "The copper distinguishs the run.",
                "The lift audits the deserted insurance.",
                "The insurance mentors the year.",
                "The night implements the room.",
                "The learning perceives the desire.",
                "The paint practices the quizzical protest.",
                "The name responds the slow place.",
                "The manager evaluates the abandoned back.",
                "The adjustment fixs the test.",
                "The print insures the rain.",
                "The fearless error automates the secretary.",
                "The bizarre wool publishs the bread.",
                "The bite operates the hour.",
                "The unusual attempt trades the slip.",
                "The waste fashions the price.",
                "The hate aides the smile.",
                "The cork logs the half woman.",
                "The development fashions the laugh.",
                "The good request nurses the meal.",
                "The loving wave reasons the expansion.",
                "The actually reading interprets the base.",
                "The worthless run fabricates the burst.",
                "The puny chance equips the river.",
                "The caring mind elicits the body.",
                "The nutritious loss officiates the porter.",
                "The nice woman transforms the degree.",
                "The family structures the cough.",
                "The defiant structure documents the end.",
                "The sleep orchestrates the river.",
                "The thin decision counsels the butter.",
                "The metal collaborates the zippy comfort.",
                "The reason writes the wood.",
                "The breath begins the cheerful water.",
                "The copy supports the nonchalant sort.",
                "The comparison collects the valuable fold.",
                "The place refines the zany motion.",
                "The synonymous servant performs the judge.",
                "The general day attains the selection.",
                "The thick salt widens the reward.",
                "The increase conceives the secret water.",
                "The apparatus encourages the comparison.",
                "The lewd destruction commences the invention.",
                "The windy science activates the art.",
                "The handy twist constructs the man.",
                "The thankful reaction investigates the mass.",
                "The imperfect history trains the sort.",
                "The glistening pain generates the destruction.",
                "The competition confers the maniacal drink.",
                "The distance decreases the guide.",
                "The rice tests the limit.",
                "The taste collaborates the education.",
                "The smell transposes the utter father.",
                "The kiss revitalizes the kick.",
                "The land reviews the grain.",
                "The jolly relation moderates the measure.",
                "The sugar methodizes the lift.",
                "The system assigns the lead.",
                "The winter fashions the care.",
                "The back summarizes the middle.",
                "The profit rectifys the unequal servant.",
                "The religion strengthens the back.",
                "The sore record co-operates the start.",
                "The insurance grants the righteous surprise.",
                "The driving filters the oval attack.",
                "The sound scrutinizes the rapid shade.",
                "The doubt set goalss the cork.",
                "The vessel broadens the dazzling blow.",
                "The group tutors the history.",
                "The system critiques the round connection.",
                "The authority greets the snobbish kick.",
                "The degree publicizes the functional number.",
                "The fiction condenses the current.",
                "The adjustment licenses the functional join.",
                "The change licenses the momentous rain.",
                "The prose troubleshots the sound.",
                "The discovery experiments the cooperative woman.",
                "The romantic sister delegates the fire.",
                "The weather projects the yielding daughter.",
                "The grass surpasss the country.",
                "The skinny test terminates the sneeze.",
                "The water monitors the helpless ornament.",
                "The history labels the extra-large wind.",
                "The low rice convinces the porter.",
                "The tax familiarizes the steel.",
                "The decorous week spokes the leather.",
                "The care maintains the pointless instrument.",
                "The doubt negotiates the blow.",
                "The zonked pain evaluates the sister.",
                "The liquid acquires the cork.",
                "The makeshift range integrates the unit.",
                "The burly sex specifys the summer.",
                "The range executes the imaginary comparison.",
                "The order evaluates the tiresome judge.",
                "The bread transforms the fast distance.",
                "The bloody event streamlines the advertisement.",
                "The bit begins the loss.",
                "The various nation attracts the reason.",
                "The profit spokes the wound.",
                "The unit imports the squeamish ink.",
                "The earth releases the fear.",
                "The work extends the devilish offer.",
                "The billowy fight helps the page.",
                "The cork schedules the song.",
                "The sulky cause predicts the insurance.",
                "The cook rehabilitates the mind.",
                "The surprise indexs the ethereal error.",
                "The belligerent government dissects the man.",
                "The manager recreates the development.",
                "The credit taughts the arrogant observation.",
                "The limit orders the attempt.",
                "The spectacular shame reviews the cry.",
                "The growth rehabilitates the shivering shame.",
                "The page wins the tidy stage.",
                "The humor considers the capable blood.",
                "The journey depicts the dusty chance.",
                "The instinctive humor canvasss the punishment.",
                "The approval rates the tense authority.",
                "The water orchestrates the heat.",
                "The copy views the chalk.",
                "The fold files the frightening night.",
                "The committee inventorys the glass.",
                "The rate applys the current.",
                "The painstaking voice inspires the hearing.",
                "The journey cultivates the kind song.",
                "The letter taughts the dysfunctional knowledge.",
                "The fire familiarizes the cloth.",
                "The learning zaps the doubt.",
                "The part orders the rule.",
                "The value decides the erect lift.",
                "The beneficial paint trains the view.",
                "The top attracts the upset tax.",
                "The disgusting representative treats the government.",
                "The likeable reading guides the lift.",
                "The distance lectures the pain.",
                "The time conciliates the penitent step.",
                "The mist retrieves the note.",
                "The kick devises the dapper meat.",
                "The start boughts the rhythm.",
                "The slippery grass licenses the surprise.",
                "The point quotes the earth.",
                "The many damage mentors the payment.",
                "The idiotic statement lobbys the cloth.",
                "The nippy cork reorganizes the note.",
                "The offer reserves the heat.",
                "The cry introduces the growth.",
                "The absorbing place zaps the way.",
                "The paper mobilizes the part.",
                "The effect details the secretive glass.",
                "The wood reviews the sedate owner.",
                "The chalk centralizes the drink.",
                "The hate listens the scarce smile.",
                "The accidental act models the song.",
                "The point litigates the copper.",
                "The slip heads the unable form.",
                "The front consults the food.",
                "The fact effects the silly gold.",
                "The business mobilizes the shame.",
                "The grass straightens the rotten fire.",
                "The thunder withdraws the gentle sound.",
                "The time attracts the oil.",
                "The even place taughts the river.",
                "The reward perceives the science.",
                "The sky filters the cynical son.",
                "The shivering self conciliates the knowledge.",
                "The harmonious meeting set ups the cork.",
                "The society demonstrates the troubled condition.",
                "The perpetual vessel lectures the verse.",
                "The powder streamlines the chubby rate.",
                "The mist releases the theory.",
                "The bite customizes the society.",
                "The ritzy thing employs the building.",
                "The account transposes the join.",
                "The account explains the invention.",
                "The danger computes the superb paste.",
                "The stage practices the awful noise.",
                "The lively story directs the process.",
                "The oil greets the merciful form.",
                "The blow acquires the act.",
                "The smile validates the guiltless place.",
                "The terrific look originates the flower.",
                "The spectacular amount catalogs the attention.",
                "The organisation expedites the high cause.",
                "The expansion displays the harmony.",
                "The careful tendency explores the hour.",
                "The night reasons the lyrical nation.",
                "The amusement catalogues the smash.",
                "The fall projects the absorbed position.",
                "The addition retrieves the language.",
                "The heat volunteers the end.",
                "The memory extrapolates the murky smoke.",
                "The shade assumes the loss.",
                "The rustic knowledge completes the education.",
                "The moldy property retains the degree.",
                "The grip catalogues the slip.",
                "The daughter probes the hearing.",
                "The prose diagrams the point.",
                "The form combines the chance.",
                "The ink examines the trite fall.",
                "The statement mediates the nice wound.",
                "The form confirms the left look.",
                "The quaint push stages the trick.",
                "The purple flower begins the judge.",
                "The distribution contracts the balance.",
                "The quality unifys the possible part.",
                "The living sign measures the road.",
                "The thirsty hope considers the sea.",
                "The expansion extrapolates the range.",
                "The disease set ups the male hole.",
                "The authority applys the bitter chalk.",
                "The month shows the flowery turn.",
                "The fight revitalizes the twist.",
                "The change set goalss the shrill look.",
                "The space inventorys the guide.",
                "The driving designs the observation.",
                "The hour revamps the cork.",
                "The onerous purpose tabulates the list.",
                "The top forecasts the pastoral protest.",
                "The business tends the pull.",
                "The science creates the tearful change.",
                "The harbor dedicates the tall twist.",
                "The cloth tabulates the mature earth.",
                "The system targets the silly night.",
                "The expansion constructs the flight.",
                "The measure acts the wash.",
                "The approval recognizes the order.",
                "The red burst revamps the push.",
                "The seat researchs the blood.",
                "The start manages the act.",
                "The luxuriant base mediates the operation.",
                "The flower adds the subdued behavior.",
                "The news volunteers the attention.",
                "The idea heads the bread.",
                "The relation invents the common request.",
                "The argument quotes the female print.",
                "The cry reinforces the mind.",
                "The minute improves the man.",
                "The back determines the far fear.",
                "The savory middle evaluates the linen.",
                "The money shapes the black hour.",
                "The fall originates the abusive insurance.",
                "The blue lift insures the edge.",
                "The rain schedules the lift.",
                "The sky categorizes the animal.",
                "The abusive manager locates the cause.",
                "The steam practices the violet silk.",
                "The pull coachs the war.",
                "The groovy experience aids the rate.",
                "The division raises the hulking pain.",
                "The observation supervises the salt.",
                "The aboard gold describes the surprise.",
                "The reaction releases the soup.",
                "The rigid error saves the unit.",
                "The tin troubleshots the sticky bit.",
                "The harbor converts the fortunate start.",
                "The view employs the dead order.",
                "The roll ranks the cool addition.",
                "The receptive shade weighs the flower.",
                "The journey installs the copy.",
                "The defeated digestion boosts the stop.",
                "The body uses the extra-small sister.",
                "The afraid fact recalls the cork.",
                "The shade treats the amount.",
                "The oceanic point appoints the religion.",
                "The balance formulates the thirsty transport.",
                "The driving invents the apparatus.",
                "The late division fosters the trade.",
                "The deeply answer amends the trouble.",
                "The important cook conciliates the expansion.",
                "The closed attempt fosters the industry.",
                "The innate purpose offsets the disgust.",
                "The kick centralizes the ambiguous crack.",
                "The transport recommends the plant.",
                "The approval assigns the subdued room.",
                "The regret establishs the copy.",
                "The language check ins the legal development.",
                "The verse narrates the record.",
                "The moaning connection transports the fold.",
                "The tax forwards the sea.",
                "The enchanting danger learns the grain.",
                "The question sustains the animal.",
                "The silk consolidates the telling mind.",
                "The stone studys the disturbed snow.",
                "The push informs the list.",
                "The push boughts the mind.",
                "The credit anticipates the lively measure.",
                "The frantic verse maximizes the space.",
                "The jelly revitalizes the long minute.",
                "The waste improves the vulgar copy.",
                "The woman bolsters the teeny-tiny sand.",
                "The astonishing coal translates the base.",
                "The push enhances the unarmed person.",
                "The feigned size listens the disgust.",
                "The jelly articulates the time.",
                "The song serves the disgust.",
                "The adventurous development obtains the humor.",
                "The loss cultivates the ubiquitous teaching.",
                "The degree shapes the sky.",
                "The tax responds the meat.",
                "The payment renders the small lift.",
                "The polish publicizes the discussion.",
                "The muddled cough joins the machine.",
                "The sassy statement enhances the lead.",
                "The taste troubleshots the harbor.",
                "The run zips the dynamic oil.",
                "The page catalogs the substantial science.",
                "The land displays the detail.",
                "The insurance obtains the father.",
                "The dispensable shade presides the sister.",
                "The closed river upgrades the law.",
                "The punishment edits the rigid insurance.",
                "The existence visits the mountain.",
                "The slim voice greets the loss.",
                "The comparison establishs the attractive meat.",
                "The education uses the drink.",
                "The plausible love aides the minute.",
                "The female paper intervenes the damage.",
                "The polish advertises the pleasant range.",
                "The sign structures the metal.",
                "The awake trade elects the flight.",
                "The literate profit allocates the daughter.",
                "The food considers the cluttered growth.",
                "The burn arbitrates the determined edge.",
                "The religion debugs the animal.",
                "The butter saves the quizzical fire.",
                "The liquid catalogs the sticky seat.",
                "The ten offer elicits the bite.",
                "The doubt zips the unknown meat.",
                "The brash current oversees the burst.",
                "The tangible surprise extracts the silver.",
                "The relieved language conducts the produce.",
                "The fear saves the night.",
                "The decision conciliates the comparison.",
                "The violet apparatus exchanges the reason.",
                "The cloudy authority evaluates the shock.",
                "The loss justifys the twist.",
                "The fast account cares the print.",
                "The paper retains the apathetic discovery.",
                "The rate rectifys the stimulating point.",
                "The hope communicates the cuddly self.",
                "The belligerent fact collates the sleep.",
                "The uncovered war specializes the lead.",
                "The zany insurance teachs the cough.",
                "The decorous winter updates the rule.",
                "The talk audits the leather.",
                "The glossy record leads the turn.",
                "The care outlines the paper.",
                "The rice convinces the porter.",
                "The paste installs the burly direction.",
                "The money discusss the strong tax.",
                "The number corrects the ready wind.",
                "The flight cultivates the sweltering disgust.",
                "The waste reveals the concerned hearing.",
                "The process expedites the loss.",
                "The religion confirms the fire.",
                "The wine values the tightfisted canvas.",
                "The mighty quality sketchs the roll.",
                "The question dissects the summer.",
                "The fluttering decision reorganizes the debt.",
                "The minute mediates the pull.",
                "The degree translates the smoke.",
                "The body elicits the addition.",
                "The nutty attack nurses the night.",
                "The flight fabricates the mother.",
                "The father symbolizes the mist.",
                "The fall streamlines the wash.",
                "The twist canvasss the thinkable touch.",
                "The man check ins the present impulse.",
                "The paint condenses the crush.",
                "The screeching company cares the secretary.",
                "The sex clarifys the encouraging body.",
                "The note specializes the paint.",
                "The daughter conveys the frequent linen.",
                "The bizarre field summarizes the motion.",
                "The bit depreciateds the brass.",
                "The milky attraction offsets the structure.",
                "The account convinces the writing.",
                "The reward judges the sleep.",
                "The person recognizes the detailed run.",
                "The sound conceptualizes the experience.",
                "The quality obtains the smell.",
                "The unequaled digestion builds the iron.",
                "The pain causes the wood.",
                "The telling mist tracks the memory.",
                "The advertisement decreases the adhesive degree.",
                "The lift overhauls the greedy way.",
                "The order inventorys the fascinated gold.",
                "The stone highlights the tedious wound.",
                "The open steam defers the market.",
                "The paltry impulse tails the rice.",
                "The needless iron strengthens the steel.",
                "The coordinated country advertises the top.",
                "The grain estimates the adhoc body.",
                "The approval conserves the amused minute.",
                "The shame structures the petite profit.",
                "The grain modifys the humor.",
                "The wind uncovers the hysterical operation.",
                "The adjustment spokes the hypnotic idea.",
                "The damage attends the statement.",
                "The billowy servant mentors the design.",
                "The rub prioritizes the jazzy name.",
                "The judge orientates the reminiscent support.",
                "The sister reads the arrogant noise.",
                "The purpose revitalizes the manager.",
                "The group educates the fretful example.",
                "The minute activates the selfish rain.",
                "The hate conducts the flight.",
                "The lead forecasts the demonic example.",
                "The point bargains the quiet polish.",
                "The instrument traces the rural blow.",
                "The comfort catalogues the punishment.",
                "The noisy edge conceives the fall.",
                "The answer amends the trouble.",
                "The scared part summarizes the twist.",
                "The wood zaps the rapid lift.",
                "The steel zaps the current.",
                "The record services the waggish apparatus.",
                "The ink specializes the edge.",
                "The brawny paste targets the record.",
                "The thoughtful butter trains the disease.",
                "The news relates the division.",
                "The curious doubt symbolizes the change.",
                "The cloudy trouble enlists the war.",
                "The best walk targets the butter.",
                "The flame presides the bit.",
                "The rice inventorys the record.",
                "The obsolete base contacts the blood.",
                "The silver mobilizes the scandalous insurance.",
                "The ten expansion unifys the cry.",
                "The prickly jelly authorizes the linen.",
                "The humor revitalizes the fiction.",
                "The knotty statement wins the roll.",
                "The strange family releases the condition.",
                "The gaping part initiates the ice.",
                "The cover uncovers the minute.",
                "The smoke accommodates the road.",
                "The filthy society exhibits the regret.",
                "The offbeat trouble trains the silver.",
                "The stone tails the existence.",
                "The start reasons the noise.",
                "The draconian group prioritizes the behavior.",
                "The move officiates the manager.",
                "The slippery learning regulates the turn.",
                "The vacuous fight donkeys the reading.",
                "The cause earns the overrated example.",
                "The design anticipates the sand.",
                "The successful paper influences the selection.",
                "The thick approval instructs the shock.",
                "The opinion rans the idea.",
                "The hearing consolidates the rain.",
                "The history develops the song.",
                "The time indexs the rhythm.",
                "The flimsy current debugs the record.",
                "The flower hires the aback walk.",
                "The simplistic surprise sketchs the love.",
                "The leather joins the nonchalant smell.",
                "The false prose bisons the order.",
                "The condition mentors the art.",
                "The direction incorporates the plucky space.",
                "The dusty damage scripts the judge.",
                "The mist diagnoses the desire.",
                "The talk estimates the minor smoke.",
                "The ahead request guides the smile.",
                "The supreme business triples the step.",
                "The profit diversifys the malicious company.",
                "The glass filters the profit.",
                "The finicky expansion estimates the quality.",
                "The flower oversees the afraid question.",
                "The credit develops the ugly peace.",
                "The gamy grass builds the government.",
                "The glass classifys the uncovered linen.",
                "The attraction lightens the accessible respect.",
                "The crush governs the lovely summer.",
                "The thick division purchases the touch.",
                "The long-term profit fashions the representative.",
                "The stop defines the offer.",
                "The beautiful hate tails the harmony.",
                "The limit fashions the like blood.",
                "The group obtains the steel.",
                "The instinctive interest minimizes the flame.",
                "The noiseless edge interfaces the power.",
                "The utopian run determines the sense.",
                "The weight solds the chalk.",
                "The leather aligns the behavior.",
                "The change authorizes the offbeat mass.",
                "The edge refines the unarmed back.",
                "The stimulating reading automates the cover.",
                "The join taughts the adjustment.",
                "The step influences the weather.",
                "The impulse navigates the vague top.",
                "The gabby cork views the copy.",
                "The run photographs the teeny-tiny experience.",
                "The amazing mind widens the fact.",
                "The month co-operates the leather.",
                "The capable chalk locates the fall.",
                "The whispering flight utilizes the crack.",
                "The trick calculates the sad smile.",
                "The week recognizes the base.",
                "The paste boosts the copy.",
                "The laugh motivates the join.",
                "The father copys the delicate level.",
                "The tax litigates the doubt.",
                "The unkempt touch examines the society.",
                "The fortunate regret solicits the expert.",
                "The cotton hosts the miniature representative.",
                "The apparatus observes the scattered food.",
                "The open trouble executes the fact.",
                "The flower visits the ray.",
                "The few ice accumulates the wash.",
                "The weight oversees the thoughtless linen.",
                "The shock advertises the poised writing.",
                "The sulky digestion zoom ins the fruit.",
                "The range accomplishs the quality.",
                "The grain cooperates the request.",
                "The weather zoom ins the existence.",
                "The voracious voice publicizes the ornament.",
                "The surprise audits the opinion.",
                "The trouble explains the father.",
                "The loss standardizes the ragged quality.",
                "The dusty journey depicts the chance.",
                "The reason trades the male roll.",
                "The polish controls the statement.",
                "The connection listens the grain.",
                "The inconclusive cause check ins the thing.",
                "The ice reconciles the purpose.",
                "The care quantifys the wound.",
                "The growth constructs the top.",
                "The distribution services the base.",
                "The art commences the rest.",
                "The hushed loss debugs the sign.",
                "The soup advertises the three thing.",
                "The steadfast tendency diagrams the error.",
                "The note shares the attraction.",
                "The smell dealt withs the ill-informed destruction.",
                "The wry memory vitalizes the offer.",
                "The smash supervises the chance.",
                "The futuristic push visualizes the harbor.",
                "The hour prioritizes the smile.",
                "The mind widens the fact.",
                "The fear appoints the careful top.",
                "The solid verse photographs the question.",
                "The grandiose look discovers the sea.",
                "The harmonious country tabulates the division.",
                "The limit simulates the iron.",
                "The disease litigates the motion.",
                "The record inventorys the harbor.",
                "The shocking kiss revitalizes the kick.",
                "The attempt accumulates the top.",
                "The belief licenses the plant.",
                "The tense smoke shares the base.",
                "The apparatus cultivates the female fold.",
                "The record leads the mysterious steel.",
                "The silver extracts the auspicious fact.",
                "The grass depicts the base.",
                "The record obtains the mundane attempt.",
                "The ablaze view refers the mother.",
                "The extra-large hour shapes the weight.",
                "The sort applys the wholesale business.",
                "The careless feeling furnishs the industry.",
                "The aggressive wind detects the manager.",
                "The sign serves the liquid.",
                "The earth recognizes the money.",
                "The self conciliates the knowledge.",
                "The unaccountable credit allocates the distribution.",
                "The chilly vessel contributes the idea.",
                "The gold maps the delicious soup.",
                "The impolite fiction updates the note.",
                "The flowery month shows the turn.",
                "The porter selects the list.",
                "The friend wins the attempt.",
                "The rub completes the aspiring roll.",
                "The language fabricates the amused lead.",
                "The birth strengthens the colorful disgust.",
                "The verse volunteers the insurance.",
                "The bread revitalizes the cluttered question.",
                "The river formulates the unable son.",
                "The canvas writes the war.",
                "The existence files the plain thunder.",
                "The nation encourages the psychedelic smoke.",
                "The night minimizes the rain.",
                "The better food considers the edge.",
                "The laugh grades the open waste.",
                "The doubt visits the rule.",
                "The act filters the thankful idea.",
                "The care summarizes the weight.",
                "The comparison spokes the next motion.",
                "The mass notifys the nation.",
                "The psychedelic point travels the education.",
                "The edge engineers the nervous quality.",
                "The superb vessel decreases the knowledge.",
                "The cloth markets the guide.",
                "The coherent system photographs the paper.",
                "The lean grain broadens the request.",
                "The digestion relateds the bite.",
                "The ray prevents the talk.",
                "The concerned meal demonstrates the reaction.",
                "The educated amount finalizes the flower.",
                "The slow damage releases the relation.",
                "The fire augments the back.",
                "The son lobbys the law.",
                "The black-and-white rhythm controls the wine.",
                "The interest communicates the earth.",
                "The change simulates the upbeat desire.",
                "The flame briefs the holistic fear.",
                "The belief combines the interesting country.",
                "The noise check outs the damage.",
                "The ten point times the punishment.",
                "The periodic advertisement extrapolates the fold.",
                "The run perfects the distance.",
                "The plant checks the massive hate.",
                "The wave attracts the electric fight.",
                "The wicked news devises the system.",
                "The trade mediates the smoke.",
                "The spotted meat defers the daughter.",
                "The shake arbitrates the fast amount.",
                "The grieving building organizes the control.",
                "The taste renews the interesting sort.",
                "The committee donkeys the aberrant butter.",
                "The base arranges the somber thought.",
                "The example debates the swanky metal.",
                "The law funds the helpful harbor.",
                "The flower directs the flight.",
                "The feeling institutes the assorted steel.",
                "The mindless sand negotiates the rest.",
                "The picayune act traces the breath.",
                "The debt publishs the place.",
                "The tart use times the decision.",
                "The unit surveys the acceptable limit.",
                "The bumpy silk builds the stitch.",
                "The voice maintains the crush.",
                "The watery heat mechanizes the disease.",
                "The front composes the son.",
                "The seat creates the account.",
                "The poised division builds the authority.",
                "The tacky family activates the relation.",
                "The oafish lead equips the comparison.",
                "The stop illustrates the secretary.",
                "The digestion articulates the observation.",
                "The secretary furnishs the sticky structure.",
                "The grass calibrates the splendid heat.",
                "The plant zone offs the grip.",
                "The sleep reports the thing.",
                "The gold enumerates the market.",
                "The leather recalls the horrible force.",
                "The needy thought screens the sleep.",
                "The annoyed request administers the expansion.",
                "The successful thought consults the letter.",
                "The wood facilitates the smell.",
                "The beautiful bit nurses the linen.",
                "The payment zoom ins the amusing sex.",
                "The condition appraises the petite protest.",
                "The trick substitutes the committee.",
                "The repulsive answer consults the statement.",
                "The axiomatic discovery attracts the system.",
                "The graceful kiss derives the cry.",
                "The protest updates the mountainous powder.",
                "The impulse helps the twist.",
                "The decision depicts the blood.",
                "The cloth exchanges the crazy care.",
                "The expert acts the swim.",
                "The side systematizes the gigantic silk.",
                "The super flame teachs the grip.",
                "The womanly voice extrapolates the relation.",
                "The value supports the attempt.",
                "The mind fortifys the crooked hope.",
                "The desire locates the family.",
                "The secretary projects the sweltering education.",
                "The rainy amusement centralizes the distribution.",
                "The discussion transforms the thinkable purpose.",
                "The deranged reward devises the offer.",
                "The purple degree shares the care.",
                "The brass discusss the air.",
                "The credit reports the odd back.",
                "The enormous swim integrates the copper.",
                "The didactic advertisement selects the operation.",
                "The utter smell transposes the father.",
                "The hearing programs the long week.",
                "The impolite end regulates the gold.",
                "The abiding music describes the morning.",
                "The point appoints the oceanic religion.",
                "The weary debt orientates the doubt.",
                "The striped opinion drews the error.",
                "The ink activates the boundless stop.",
                "The hushed level projects the approval.",
                "The black-and-white chalk maintains the teaching.",
                "The part develops the nonstop paint.",
                "The lacking grain modifys the humor.",
                "The eager porter uncovers the cough.",
                "The opinion localizes the tired space.",
                "The doubt solicits the unable writing.",
                "The tin produces the owner.",
                "The end composes the reminiscent harmony.",
                "The small structure canvasss the experience.",
                "The bite revises the look.",
                "The point quotes the note.",
                "The scale facilitates the front.",
                "The detail quotes the insidious room.",
                "The approval executes the jazzy animal.",
                "The truthful night implements the room.",
                "The understood system tends the division.",
                "The part weighs the stage.",
                "The advertisement records the literate ornament.",
                "The chance enlarges the attention.",
                "The meal corresponds the bread.",
                "The nice tendency engineers the fight.",
                "The energetic polish speaks the lift.",
                "The animal learns the next slip.",
                "The burn assigns the nation.",
                "The attempt transposes the marvelous flame.",
                "The holistic flame briefs the fear.",
                "The effect estimates the discussion.",
                "The mind orientates the wooden fall.",
                "The observation advises the stretch.",
                "The tendency plans the payment.",
                "The amusement reduces the damp grass.",
                "The porter cultivates the thundering summer.",
                "The fear detects the maddening soup.",
                "The canvas surpasss the charming law.",
                "The twist rans the step.",
                "The receptive mother accumulates the cause.",
                "The voice theorizes the melodic detail.",
                "The guide achieves the care.",
                "The fragile attention offsets the laugh.",
                "The profit projects the female fear.",
                "The voice inspires the hearing.",
                "The country charges the weight.",
                "The pointless slip records the shame.",
                "The forgetful cook samples the start.",
                "The fight files the nebulous waste.",
                "The shaggy judge sketchs the control.",
                "The finicky knowledge substitutes the value.",
                "The evasive lift predicts the opinion.",
                "The observation plans the thing.",
                "The industry funds the amusement.",
                "The current uncovers the cool slip.",
                "The road plans the rate.",
                "The fiction enlarges the slim time.",
                "The act grants the wood.",
                "The rest establishs the aggressive question.",
                "The machine judges the didactic smile.",
                "The paper measures the change.",
                "The nutritious record debugs the range.",
                "The vengeful knowledge anticipates the protest.",
                "The miscreant price appoints the list.",
                "The zealous fear plans the apparatus.",
                "The phobic lift draws the twist.",
                "The time discloses the art.",
                "The law tours the machine.",
                "The color troubleshots the committee.",
                "The guide set ups the direction.",
                "The secretary diversifys the stretch.",
                "The cork supports the burst.",
                "The night depreciateds the cloth.",
                "The plausible religion taughts the process.",
                "The level considers the deranged sugar.",
                "The flower lobbys the macho poison.",
                "The secretary straightens the handy request.",
                "The division streamlines the cooperative competition.",
                "The note recommends the racial reason.",
                "The wrathful rate draws the crack.",
                "The loving family taughts the property.",
                "The wood relateds the river.",
                "The well-to-do ray orientates the shock.",
                "The measure times the organisation.",
                "The manager reports the smiling rice.",
                "The fire substantiates the answer.",
                "The twist collects the system.",
                "The sand tests the year.",
                "The afraid butter defines the war.",
                "The exclusive theory revitalizes the land.",
                "The ice qualifys the direction.",
                "The music automates the deadpan note.",
                "The day conciliates the expert.",
                "The connection accommodates the representative.",
                "The industry contracts the loud fight.",
                "The hearing specializes the heat.",
                "The care diagrams the fanatical print.",
                "The gifted back summarizes the middle.",
                "The linen recalls the historical reaction.",
                "The name frames the watery middle.",
                "The owner detects the direful system.",
                "The burn co-operates the hallowed time.",
                "The cynical sex develops the form.",
                "The cook conciliates the expansion.",
                "The division starts the concerned cotton.",
                "The slope travels the tense view.",
                "The absent letter examines the top.",
                "The groovy back comforts the adjustment.",
                "The accurate behavior prevents the disease.",
                "The name validates the periodic competition.",
                "The look refers the abandoned operation.",
                "The rain retains the deafening person.",
                "The company projects the instinctive direction.",
                "The blue-eyed print originates the fall.",
                "The fear distinguishs the ornament.",
                "The self applys the square sense.",
                "The part modernizes the trade.",
                "The gold contributes the pushy love.",
                "The instrument substantiates the voice.",
                "The question governs the way.",
                "The cotton observes the absurd view.",
                "The powerful glass bisons the push.",
                "The tin produces the melodic owner.",
                "The iron aides the frightening level.",
                "The scale facilitates the ugliest front.",
                "The swim negotiates the equal danger.",
                "The reason checks the record.",
                "The advertisement decreases the adhesive degree.",
                "The lift overhauls the greedy way.",
                "The order inventorys the fascinated gold.",
                "The stone highlights the tedious wound.",
                "The open steam defers the market.",
                "The paltry impulse tails the rice.",
                "The needless iron strengthens the steel.",
                "The coordinated country advertises the top.",
                "The grain estimates the adhoc body.",
                "The approval conserves the amused minute.",
                "The shame structures the petite profit.",
                "The grain modifys the humor.",
                "The wind uncovers the hysterical operation.",
                "The adjustment spokes the hypnotic idea.",
                "The damage attends the statement.",
                "The billowy servant mentors the design.",
                "The rub prioritizes the jazzy name.",
                "The judge orientates the reminiscent support.",
                "The sister reads the arrogant noise.",
                "The purpose revitalizes the manager.",
                "The group educates the fretful example.",
                "The minute activates the selfish rain.",
                "The hate conducts the flight."
            };
            
            Log.AddLogFile("log.txt");
            Log.Instance().LogLevel = Log.Elevation.Verbose;
            // Log.Instance().LogLevel = Log.Elevation.Debug;
            
            Log.Info("Starting ...");
            
            var gateway = new GatewayListener("wss://gateway.discord.gg/", token);
            var api = new API(new Authentication(Authentication.AuthType.Bot, token));

            var counters = new Dictionary<ulong, int>();
            
            gateway.OnMessageCreate += eventArgs =>
            {
                Log.Verbose("Thread Start: " + Thread.CurrentThread.Name);
                if (!counters.ContainsKey(eventArgs.Message.channel_id))
                    counters[eventArgs.Message.channel_id] = 1;
                else
                    counters[eventArgs.Message.channel_id]++;

                Log.Verbose("Counter for " + eventArgs.Message.channel_id + ": " + counters[eventArgs.Message.channel_id]);

                if (counters[eventArgs.Message.channel_id] % 10 != 0)
                {
                    Log.Verbose("Thread End: " + Thread.CurrentThread.Name);
                    return;
                }
                var rand = new Random();
                var pos = rand.Next(0, sentences.Length - 1);
                var msgPayload = new CreateMessageParams {content = sentences[pos]};
                Log.Verbose("Sending msg", "message.create");
                api.Channel.CreateMessage(eventArgs.Message.channel_id, msgPayload);
                Log.Verbose("Message sent!", "message.create");
                
                Log.Verbose("Thread End: " + Thread.CurrentThread.Name);
            };
            
            /* gateway.OnMessageCreate += eventArgs =>
            {
                Log.Info(eventArgs.Message.author.username + ": " + eventArgs.Message.content, "message");
            }; */
            
            // gateway.StartListeningAsync().Wait();

            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz1" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz2" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz3" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz4" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz5" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz6" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz7" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz8" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz9" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz10" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz11" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz12" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz13" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz14" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz15" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz16" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz17" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz18" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz19" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz20" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz21" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz22" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz23" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz24" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz25" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz26" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz27" });
            api.Channel.CreateMessage(130638711930093568, new CreateMessageParams{ content = "lolz28" });
            
            Log.Info("Closed.");
        }
    }
}
